# Generated by Django 4.2.7 on 2026-05-18 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='like',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Approved by moderator'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured on homepage'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Visible to all users'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['photo', '-created_at'], name='gallery_com_photo_i_cb6e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user', '-created_at'], name='gallery_com_user_id_a0e7bf_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='gallery_com_created_373226_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user', 'photo'], name='gallery_lik_user_id_fe2310_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['-created_at'], name='gallery_lik_created_ee50cb_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['user', '-created_at'], name='gallery_pho_user_id_a7e514_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['-created_at'], name='gallery_pho_created_1e6ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['is_approved', '-created_at'], name='gallery_pho_is_appr_2ce814_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['slug'], name='gallery_pho_slug_931ebf_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['views_count'], name='gallery_pho_views_c_c58077_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['likes_count'], name='gallery_pho_likes_c_5f7003_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='gallery_tag_name_2a271b_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='gallery_tag_slug_90ef48_idx'),
        ),
        migrations.AddField(
            model_name='photoview',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='gallery.photo'),
        ),
        migrations.AddField(
            model_name='photoview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='photoview',
            index=models.Index(fields=['photo', '-viewed_at'], name='gallery_pho_photo_i_73dd8b_idx'),
        ),
        migrations.AddIndex(
            model_name='photoview',
            index=models.Index(fields=['viewed_at'], name='gallery_pho_viewed__bc4dd4_idx'),
        ),
    ]
