# Generated by Django 4.2.7 on 2026-05-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='Cloudinary thumbnail URL', max_length=500),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.URLField(help_text='Cloudinary image URL', max_length=500),
        ),
    ]
